# Generated by Django 5.2 on 2025-04-23 01:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_profile_grade_profile_identification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permissionsgroup',
            name='permissions_id',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='image',
        ),
        migrations.CreateModel(
            name='Candidates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('code', models.CharField(default='', max_length=10)),
                ('votes', models.IntegerField(default=0)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_profile', to='Users.profile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Permissions',
        ),
        migrations.DeleteModel(
            name='PermissionsGroup',
        ),
    ]
