# Generated by Django 5.2 on 2025-05-25 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_remove_permissionsgroup_permissions_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidates',
            name='description',
            field=models.TextField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='candidates',
            name='image',
            field=models.ImageField(default='candidates/default.png', upload_to='candidates/'),
        ),
    ]
