# Generated by Django 5.2 on 2025-07-22 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_candidates_description_candidates_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidates',
            name='code',
        ),
        migrations.AddField(
            model_name='candidates',
            name='percentage',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='profile',
            name='voted_comptroller',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='voted_ombudman',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='candidates',
            name='image',
            field=models.ImageField(default='candidates/default_candidate.webp', upload_to='candidates/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='identification',
            field=models.IntegerField(default=0, unique=True),
        ),
    ]
