# Generated by Django 5.2 on 2025-07-22 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0005_remove_candidates_code_candidates_percentage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidates',
            name='role',
            field=models.CharField(choices=[('Personería', 'Personería'), ('Contraloría', 'Contraloría')], default='Personería', max_length=20),
        ),
    ]
